spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect